Deploy after successful build

diff --git a/Automation/Jenkinsfile b/Automation/Jenkinsfile
--- a/Automation/Jenkinsfile
+++ b/Automation/Jenkinsfile
@@ -55,6 +55,89 @@ node("hubot")
 
   // Clone the repo
   git credentialsId: 'github-cred', url: "${git_url}", branch: "${branch}"
+  
+  /***************************************************************************************************
+  ****************************************************************************************************
+  * Build Ruby Stage
+  ****************************************************************************************************
+  ***************************************************************************************************/
+  stage("BundleInstall")
+  {
+    sh "echo '#########################################'"
+    sh "echo 'Running Bundle Install'"
+    sh "echo '#########################################'"
+
+    try
+    {
+       // run the build
+      sh "chmod +x Automation/bundle-install.sh ; ./Automation/bundle-install.sh"
+    }
+    catch(all)
+    {
+      echo "ERROR encountered during ruby bundle install"
+      throw all
+      foundErrors=1
+    }
+  }
+
+  /***************************************************************************************************
+  ****************************************************************************************************
+  * Generate and Configure DB Stage
+  ****************************************************************************************************
+  ***************************************************************************************************/
+  stage("Generate And Configure DB")
+  {
+    sh "echo '#########################################'"
+    sh "echo 'Generating and configuring Postgres DB'"
+    sh "echo '#########################################'"
+
+    try
+    {
+      // run the build
+      sh "chmod +x Automation/configure-install-db.sh ; ./Automation/configure-install-db.sh"
+    }
+    catch(all)
+    {
+      echo "ERROR encountered during ruby db config"
+      throw all
+      foundErrors=1
+    }
+  }
+
+  /***************************************************************************************************
+  ****************************************************************************************************
+  * Run RSPEC Stage
+  ****************************************************************************************************
+  ***************************************************************************************************/
+  stage("Run RSPEC")
+  {
+    sh "echo '#########################################'"
+    sh "echo 'Running Ruby RSPEC'"
+    sh "echo '#########################################'"
+
+    try
+    {
+      // run the build
+      sh "chmod +x Automation/run-rspec.sh ; ./Automation/run-rspec.sh"
+    }
+    catch(all)
+    {
+      echo "ERROR encountered during ruby rspec"
+      throw all
+      foundErrors=1
+    }
+  }
+
+  /***************************************************************************************************
+  ****************************************************************************************************
+  * Validate if errors found
+  ****************************************************************************************************
+  ***************************************************************************************************/
+  if(foundErrors=='1')
+  {
+    sh "echo 'ERROR! Failed to Build Ruby App' && exit 911"
+  }
+
 
   /***************************************************************************************************
   ****************************************************************************************************
@@ -151,88 +234,7 @@ node("hubot")
   }
 
 
-  /***************************************************************************************************
-  ****************************************************************************************************
-  * Build Ruby Stage
-  ****************************************************************************************************
-  ***************************************************************************************************/
-  stage("BundleInstall")
-  {
-    sh "echo '#########################################'"
-    sh "echo 'Running Bundle Install'"
-    sh "echo '#########################################'"
-
-    try
-    {
-       // run the build
-      sh "chmod +x Automation/bundle-install.sh ; ./Automation/bundle-install.sh"
-    }
-    catch(all)
-    {
-      echo "ERROR encountered during ruby bundle install"
-      throw all
-      foundErrors=1
-    }
-  }
-
-  /***************************************************************************************************
-  ****************************************************************************************************
-  * Generate and Configure DB Stage
-  ****************************************************************************************************
-  ***************************************************************************************************/
-  stage("Generate And Configure DB")
-  {
-    sh "echo '#########################################'"
-    sh "echo 'Generating and configuring Postgres DB'"
-    sh "echo '#########################################'"
-
-    try
-    {
-      // run the build
-      sh "chmod +x Automation/configure-install-db.sh ; ./Automation/configure-install-db.sh"
-    }
-    catch(all)
-    {
-      echo "ERROR encountered during ruby db config"
-      throw all
-      foundErrors=1
-    }
-  }
-
-  /***************************************************************************************************
-  ****************************************************************************************************
-  * Run RSPEC Stage
-  ****************************************************************************************************
-  ***************************************************************************************************/
-  stage("Run RSPEC")
-  {
-    sh "echo '#########################################'"
-    sh "echo 'Running Ruby RSPEC'"
-    sh "echo '#########################################'"
-
-    try
-    {
-      // run the build
-      sh "chmod +x Automation/run-rspec.sh ; ./Automation/run-rspec.sh"
-    }
-    catch(all)
-    {
-      echo "ERROR encountered during ruby rspec"
-      throw all
-      foundErrors=1
-    }
-  }
-
-  /***************************************************************************************************
-  ****************************************************************************************************
-  * Validate if errors found
-  ****************************************************************************************************
-  ***************************************************************************************************/
-  if(foundErrors=='1')
-  {
-    sh "echo 'ERROR! Failed to Build Ruby App' && exit 911"
-  }
-
+  
   /***************************************************************************************************
   ****************************************************************************************************
   * END OF LOOP
